<?php

/**
 * @file
 * Placeholder module file.
 */

/**
 * Implements hook_element_info_alter().
 */
function placeholder_element_info_alter(&$types) {
  // Add placeholder support to textfields and textareas.
  foreach (array_keys($types) as $type) {
    switch ($type) {
      case 'textfield':
      case 'textarea':
        $types[$type]['#process'][] = 'placeholder_process_placeholder';
        break;
    }
  }
}

/**
 * Element process callback; adds support for the HTML5 placeholder attribute.
 *
 * @param $element
 *   An associative array containing the properties of the element.
 *
 * @return
 *   The processed element.
 */
function placeholder_process_placeholder($element) {
  if (isset($element['#placeholder']) && !isset($element['#attributes']['placeholder'])) {
    // If the placeholder FAPI property is set, simply add it to the form's
    // attributes so it will be output in the HTML tag.
    $element['#attributes']['placeholder'] = $element['#placeholder'];
    // Add the library if it's available.
    if (($library = libraries_load('placeholder', 'minified')) && !empty($library['loaded'])) {
      libraries_load_files($library);
      // Attach our js file, to actually use the library.
      $element['#attached']['js'] = array(
        drupal_get_path('module', 'placeholder') . '/placeholder.js',
      );
    }
  }
  return $element;
}

/**
 * Implements hook_libraries_info().
 */
function placeholder_libraries_info() {
  $libraryes = array();

  $libraries['placeholder'] = array(
    'title' => 'jQuery-Placeholder', 
    'vendor url' => 'https://github.com/danielstocks/jQuery-Placeholder', 
    'version' => '1.0',
    'files' => array(
      'js' => array(
        'jquery.placeholder.js',
      ),
    ),
    'variants' => array(
      'minified' => array(
        'files' => array(
          'js' => array(
            'jquery.placeholder.min.js',
          ),
        ),
      ),
    ),
  );

  return $libraries;
}

function placeholder_form_search_block_form_alter(&$form, &$form_state) {
  $form['search_block_form']['#placeholder'] = t('Search...');
}
